[alembic]
script_location = app/db/migrations
sqlalchemy.url = sqlite:///./app/bridge.db
target_metadata = app.db.models.Base.metadata

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname = root

[logger_sqlalchemy]
level = WARNING
handlers = console
qualname = sqlalchemy

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
